### ISSUE TITLE
`make run` does not work in Rodinia Hotspot example on Windows

### ISSUE THREAD

**Issue by mrakgr** [HIPERFIT/futhark-benchmarks#3]
This is possibly the most trivial example of a bug I've yet to report.

It can easily be fixed by changing the `./hotspot-gui.py 800` into `python ./hotspot-gui.py 800`, in the last line. With this I've gone through the four example and not much remains for me, but to start learning Haskell if I want to really dive deeper into the language. I think I have a decent grasp of it now, though I won't be able to contribute anything substantial until I get myself up to par.

**Comment by nqpz** [comment]
Thank you for pointing the non-portability out.  I have fixed this in commit 8294eabccf73b106bfa14654f5676e896afc1633.

And you should learn Haskell.  It's fun!
