### ISSUE TITLE
https://github.com/HIPERFIT/futhark-benchmarks.git

### ISSUE THREAD

**Issue by LaurentPlagne** [HIPERFIT/futhark-benchmarks#7]
Hi,
After a fresh install of futhark and futhark-benchmark
futhark-bench is OK but
futhark-bench --compiler=futhark-opencl produces syntax error like
`./jgf/crypt/keys.bin: Syntax error when reading []i16.`
I wonder if my openCL installation is OK...
In addition, how can I select the device between my CPU, iGPU and GPU OpenCL targets ?
Laurent

**Comment by Athas** [comment]
That's weird.  Are you sure you have the newest version of both Futhark and `futhark-benchmark`?  Are the files `jgf/crypt/crypt-data/userkey0.txt` and `jgf/crypt/crypt/data/keys0.txt` intact?  What is your operating system?  The generated code uses `"%"SCNi16` with `scanf()` to read `i16` values, which I think works everywhere.

**Comment by LaurentPlagne** [comment]
I will try a complete reinstall. Not now because I realize that I should probably avoid spending all my WE in front of the computer ;)
Thank you very much for your support and enjoy your WE !

**Comment by LaurentPlagne** [comment]
OK my problem is not related with futhark-benchmarks... I post it again in futhark
